pipeline {
    agent any
    environment {
        IMAGE = "docker.io/longbugi/gitops-demo"
        TAG = "${BUILD_NUMBER}"
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/longbugi/Sysad.LongPD.git'
            }
        }
        stage('Build Image') {
            steps {
                sh 'docker build -t $IMAGE:$TAG .'
            }
        }
        stage('Push Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'longbugi',
                    passwordVariable: 'satzu2912')]) {
                    sh '''
                    echo $PASS | docker login -u $USER --password-stdin
                    docker push $IMAGE:$TAG
                    '''
                }
            }
        }
        stage('Update Helm') {
            steps {
                sh """
                sed -i 's/tag:.*/tag: ${TAG}/' Bai42.CD/chart/values.yaml
                git config user.email "jenkins@lab.local"
                git config user.name "jenkins"
                git add .
                git commit -m "Update image ${TAG}"
                git push
                """
            }
        }
    }
}
